### ISSUE TITLE
Going back and next on "mnemonic phrase confirmation" does not reset the 24 word boxes correctly

### ISSUE THREAD

**Issue by dasource** [particl/partgui#117]
When going back and next this generates a new mnemonic as it should however the state of the boxes is not reset and this results in fields with words that are not locked.

It should reset the state of the 24 boxes, before repopulating and then locking the relevant fields.

**Comment by HenkSwardt** [comment]
Kirti is looking into this for us

**Comment by rynomster** [comment]
#128 fixes this
