### ISSUE TITLE
Account Restore says "couldn't connect to Particl Daemon"

### ISSUE THREAD

**Issue by dasource** [particl/partgui#118]
When restoring I get the error "couldn't connect to Particl Daemon".
There is no way to exit this screen without closing down the interface. I can clearly see the daemon is connected as the Sync Bar at the bottom is progressing.

Also when I check the daemon directly I can see that the restore did indeed complete and the account was created.

**Comment by HenkSwardt** [comment]
Vikas is looking into this for us

**Comment by rynomster** [comment]
Fixed on master. It was related to a rpc timeout, only affects slow PCs
