### ISSUE TITLE
"partgui" everywhere

### ISSUE THREAD

**Issue by dasource** [particl/partgui#119]
Installer, Header, Filename etc all say "partgui" vs Partical Wallet? (or Partical Electron Wallet)

**Comment by HenkSwardt** [comment]
Kirti is looking into this for us

**Comment by anandsinghparihar** [comment]
I am going to change everywhere partgui to >>> Partical Wallet

**Comment by anandsinghparihar** [comment]
Install means a package manager file, 
Heder means title of page
I do not understand what is FileName, I can see only a repository  name is `partgui` ;)

**Comment by HenkSwardt** [comment]
Kirti, Please make sure it is Particl Electron Wallet

**Comment by rynomster** [comment]
It should be Particl Wallet

**Comment by HenkSwardt** [comment]
Sorry for confusion, Please can we make it "Particl Wallet" as discussed.

**Comment by anandsinghparihar** [comment]
Done Please check : [https://github.com/particl/partgui/pull/129 ](url)

**Comment by rynomster** [comment]
#129 closes this
