### ISSUE TITLE
Receive Page - QR code size (huge) when no address/wallet

### ISSUE THREAD

**Issue by dasource** [particl/partgui#120]
If there is no wallet the page should show up as such and ask the user to create a new/restore wallet.
This should apply to Send, History and Address Book page also.

**Comment by kewde** [comment]
We'll make it generate an address on wallet creation

**Comment by dasource** [comment]
Still need to address the "no wallet" condition.

**Comment by HenkSwardt** [comment]
Vikas is looking into this for us

**Comment by vikas-cis** [comment]
fixed #148
