### ISSUE TITLE
Encrypt Wallet error

### ISSUE THREAD

**Issue by dasource** [particl/partgui#121]
After entering the password twice to encrypt the wallet you get a "couldn't connect to Particl Daemon"
Not very user intuitive - User should be told or the App should auto restart?

**Comment by kewde** [comment]
encryptwallet indeed shuts down the wallet, that needs fixing or atleast a warning message

**Comment by HenkSwardt** [comment]
Vikas is looking at this issue

**Comment by rynomster** [comment]
This one is quite complex.. we need to restart the daemon somehow after encryption.
It involves modules/rpc and modules/clientBinary
You'll need to restart the daemon, same way as its started at startup.

**Comment by kewde** [comment]
The backend can detect the walletpassphrase command passing through IPC and execute a reboot of the daemon after encryption.

**Comment by rynomster** [comment]
Yes that's what I suggested, but there is a whole startup sequence for the
daemon. We want to introduce a daemon management screen, that can stop,
start and change parameters for the daemon.

**Comment by kewde** [comment]
I don't think the daemon management screen is a good idea if it's going to pass parameters straight into the command line.

**Comment by rynomster** [comment]
We wouldn't pass parameters to the command line no.. it would reuse the current daemon startup code.

**Comment by HenkSwardt** [comment]
Please confirm that this has been resolved?

**Comment by rynomster** [comment]
It seems now we have an issue where the unlock doesn't work properly, or the state doesn't work properly when you restart the daemon.
