### ISSUE TITLE
"couldn't connect to Particl Daemon"

### ISSUE THREAD

**Issue by dasource** [particl/partgui#122]
Rather than displaying this error on a full screen modal page which sometimes results in having to shutdown the app (the x does not always display top right) we should have a small popup widget (like bittrex order filled ones) which shows when the device has lost connection to the daemon (and it should always remain there whilst the connection is lost) - should check every X/secs to see if the connection is restored.

**Comment by kewde** [comment]
The whole GUI is kinda useless in the state, it should never lose the connection to the RPC (it's local). If it is in that state then it seems wiser to just disable access.

**Comment by dasource** [comment]
I clearly seems to be happening and due to the way it is being handled it leaves the user no choice but to shutdown the app. It makes no sense to have a smaller popup which check periodically and if it is lost (grays interface) and restored (the interface becomes usable again).

in 10mins, I have seen the error 3-4 times and the daemon is responding fine in the background.

**Comment by HenkSwardt** [comment]
Vikas is looking into this for us

**Comment by rynomster** [comment]
We added the X. Enable close was being disabled in the wallet creation process. The error modal was showing up due to an RPC timeout on slow machines.
