### ISSUE TITLE
Receive - Private Tab

### ISSUE THREAD

**Issue by dasource** [particl/partgui#124]
What are private addresses? it seems to show an address starting with SPG (looks like stealth) and the New Private Address modal does nothing.

**Comment by kewde** [comment]
Works fine for me here..
I'm using the current master

**Comment by dasource** [comment]
Ahh I though it was dummy text since the "new modal" was not working. After restarting it is now and makes more sense. Closing.

**Comment by kewde** [comment]
@dasource 
What SPG address? This may just be the cold staking address you've entered.
Already parsing those out in the coldstaking PR
