### ISSUE TITLE
Incorrect wallet naming in various locations

### ISSUE THREAD

**Issue by imybb** [particl/partgui#136]
![particl_install](https://user-images.githubusercontent.com/30150617/31055173-a5c9bdae-a6b7-11e7-8194-10b01c0f96ed.png)
![particl_start_menu](https://user-images.githubusercontent.com/30150617/31055174-a5ca4dd2-a6b7-11e7-8539-5d5eca816c94.png)
![particl_control_panel_uninstall_window](https://user-images.githubusercontent.com/30150617/31055175-a5ca728a-a6b7-11e7-8fea-7c7e3f1ad539.png)
![particl_gui_taskbar](https://user-images.githubusercontent.com/30150617/31055228-f982db60-a6b7-11e7-9702-03f94e798700.png)

**Comment by rynomster** [comment]
That can't be changed. Electron builder takes a single name, no spaces. We
can call it ParticlWallet, particl-wallet, or something similar, but not
Particl Wallet.. particl is next best

**Comment by imybb** [comment]
I see, should we call it Particl rather than particl?

**Comment by HenkSwardt** [comment]
Yes, I also think capitalize "Particl".

**Comment by rynomster** [comment]
We can have a look at how we can change the build script to name it correctly

**Comment by vikas-cis** [comment]
Fix #148 I have changed particl to Particl , Let me know if that looks good :)

**Comment by vikas-cis** [comment]
Valid Fix at discuss with Ryno here Fix #149

**Comment by HenkSwardt** [comment]
Issue has been resolved, this can be closed.
