### ISSUE TITLE
Total received, should it return a value?

### ISSUE THREAD

**Issue by imybb** [particl/partgui#137]
![particl_gui_total_received](https://user-images.githubusercontent.com/30150617/31055313-d448c8d6-a6b8-11e7-831d-63e64776a0d6.png)

**Comment by kewde** [comment]
Might be be removed, it has to do a call for every address, it becomes very API intensive.
There might be some ways to reduce the load tho.

**Comment by vikas-cis** [comment]
Fix #149  I have removed the html that shows Total received with plus 0 , Please let me know if there is plan to call api or something to show value in place of zero.

**Comment by HenkSwardt** [comment]
Issue has been resolved, this can be closed.
