### ISSUE TITLE
negative part amount (balance transfer)

### ISSUE THREAD

**Issue by kapsr** [particl/partgui#138]
![5](https://user-images.githubusercontent.com/32437236/31057093-2799bfe4-a6dd-11e7-98ed-173dfd493c96.jpg)

This should be avoided, no reason to validate a negative balance transfer. Current error message is not user friendly either

**Comment by vikas-cis** [comment]
fix #148

**Comment by HenkSwardt** [comment]
Issue has been resolved, this can be closed.
