### ISSUE TITLE
Radio buttons (tab: balance transfer) between from/to account not properly configured

### ISSUE THREAD

**Issue by kapsr** [particl/partgui#139]
There are a couple inconsistencies here.

1: 'From'- and 'To' account are default set to 'Public' when opening this tab. 
However, after switching 'To' account from 'Public' to 'Blind', 'Public' is not selectable anymore (when trying to switch back). Why were these radio buttons set to public / public by default when opening this tab in the first place? There is a workaround however: Set 'From' to 'Blind', now set 'To' back to 'Public'. 'From' can now be set back to Public. This seems to be a bug/workaround for something you wanted to prevent the user from doing.

2: I'm able to select 'Private' in both 'From' and 'To' account, this differs from the above example. Why?

**Comment by kewde** [comment]
The UX was setten up such that you wouldn't be able to select two of the same kind.
This was working perfectly a few weeks ago, I'll look into what's happened.

**Comment by vikas-cis** [comment]
I have fix the issue #148 , I have configured the radio input so user cannot able to check the same from and too, Please have a look and let me know 
Thanks

**Comment by HenkSwardt** [comment]
Issue has been resolved, this can be closed.
