### ISSUE TITLE
Icons need mouseover (UX suggestion)

### ISSUE THREAD

**Issue by kapsr** [particl/partgui#140]
![7](https://user-images.githubusercontent.com/32437236/31057184-b42c6866-a6de-11e7-9178-fccde5368480.jpg)
![8](https://user-images.githubusercontent.com/32437236/31057185-b5fd782e-a6de-11e7-97e1-e8bbaa950ddd.jpg)

**Comment by HenkSwardt** [comment]
This issue has been resolved in https://github.com/particl/partgui/pull/155

**Comment by kapsr** [comment]
![mouseover](https://user-images.githubusercontent.com/32437236/32138458-6062e6b4-bc33-11e7-9dc6-53733d56dcfa.jpg)
In the latest build, mouseover is working for all icons. Except for the above icon (Its also not green anymore compared to the default green color before)

**Comment by HenkSwardt** [comment]
Good day @kapsr 

Thank you for the feedback, The above is a known issue that we are looking into. 

Regards
