### ISSUE TITLE
Advanced options need 'advanced' indicator (UX suggestion)

### ISSUE THREAD

**Issue by kapsr** [particl/partgui#141]
![advanced1](https://user-images.githubusercontent.com/32437236/31057236-ca83ed9a-a6df-11e7-885f-d01f0d1387a8.jpg)
![9](https://user-images.githubusercontent.com/32437236/31057237-cbee6a20-a6df-11e7-92e9-3ae7f187ea31.jpg)

**Comment by vikas-cis** [comment]
Fix #149 I have hide the advanced option in send transfer tab.Secondly for indicating advanced option refers to pay to option, I have changed the text as discuss with Henk :)
Please check and provide me your suggestions.
Thanks

**Comment by HenkSwardt** [comment]
Issue has been resolved, this can be closed.
