### ISSUE TITLE
Close symbol upper right corner is very small/faint (UX suggestion)

### ISSUE THREAD

**Issue by kapsr** [particl/partgui#142]
![untitled-6](https://user-images.githubusercontent.com/32437236/31057284-8521ef62-a6e0-11e7-8a12-70b53fde2631.jpg)

**Comment by rynomster** [comment]
Are you running UHD?

**Comment by kapsr** [comment]
correct, though everything else seems to scale well.

**Comment by rynomster** [comment]
This is fixed in the [develop branch](/particl/partgui/tree/develop)
