### ISSUE TITLE
Menu unpinning: UX improvement

### ISSUE THREAD

**Issue by kapsr** [particl/partgui#143]
1. To me as a user, this feels weird. Either de-pin and collapse both frames at the same time when mouse is still on the pin icon, or preferably collapse both at the same time when mouse leaves the pin icon. Currently, the info displayed on the right frame becomes partly hidden behind the left frame (menu) when mouse is still on menu. It stays partly hidden when the menu is exposed again. i think all info on the right frame should always be displayed, no matter if the menu is exposed or not.

2. Maybe add a mouseover with info on the pin button (Pin menu / Hide menu)

**Comment by kewde** [comment]
Keeps titles short and sweet please.

**Comment by rynomster** [comment]
This will be fixed on the material branch, once we switch over.

**Comment by HenkSwardt** [comment]
This issue is being addressed in https://github.com/particl/partgui/pull/189 (https://particl.atlassian.net/browse/PAR-234)
