### ISSUE TITLE
Radio buttons 'From account' (between Send payment-/Balance transfer tabs) appear to be dependent/buggy

### ISSUE THREAD

**Issue by kapsr** [particl/partgui#145]
Go to Send, From account is set to Public by default (no privacy bar visible)
Now go to tab Balance transfer and select From account: Private (privacy bar becomes visible)
So far so good...

Navigate back to tab send payment: The privacy bar is now visible here while no radio button is selected (remember: default was public before and no privacy bar was visible). 

I think you want to make these two tabs completely independent.

**Comment by vikas-cis** [comment]
fix #148 please check and let me know

**Comment by HenkSwardt** [comment]
Issue has been resolved, this can be closed.
