### ISSUE TITLE
Single nor double clicking the part icon in system tray (Windows 10) will move/reveal the Part Gui in front of other windows

### ISSUE THREAD

**Issue by kapsr** [particl/partgui#146]
All other apps i run on my computer which are displayed in system tray will actually move forward/show up after clicking once or twice, except the Part GUI. With system tray i refer to the right menu (where you find power management, sound, language bar et cetera).

**Comment by vikas-cis** [comment]
Fix #149 please check and let me know

**Comment by HenkSwardt** [comment]
Issue has been resolved, this can be closed.

**Comment by kapsr** [comment]
This issue has re-appeared in latest build.
