### ISSUE TITLE
Material GUI bugs.

### ISSUE THREAD

**Issue by HenkSwardt** [particl/partgui#154]
Working through the Material GUI, a number of issues has been picked up that needs attention, Please have a look at the points below. 

**Send Page:**

1. Making a payment is not possible, nothing happens after selecting the make payment button
2. Pay To field, Paste button: Tootltip says copy, should be paste
3. Pay To field, Paste button: Icon suggests copy action, change to paste icon

**History Page:**

1. Transactions are duplicated

**Overview Page:**

1. Transactions are duplicated

**Create new Wallet- Write down recovery phrase step:**

1. No tooltip on copy button
2. No pointer icon on copy button

**Create new Wallet- Enter Phrase step:**

1. After entering phrases and selecting button, nothing happens

**Comment by anandsinghparihar** [comment]
Please consider Send page task has done :)

**Comment by HenkSwardt** [comment]
All issues have been resolved
