### ISSUE TITLE
Unlock Password off centre

### ISSUE THREAD

**Issue by FrancoisOdendaal** [particl/partgui#156]
The wallet unlock interface is not center alligned when it is reached from the Restore Wallet and Create Wallet action:

![image](https://user-images.githubusercontent.com/32632469/31483617-688defe0-af2d-11e7-8c00-d3c22ccf1a9f.png)

**Comment by rynomster** [comment]
This is on the develop branch

**Comment by allienworks** [comment]
Fixed.
