### ISSUE TITLE
"Nexr" buttons typo

### ISSUE THREAD

**Issue by FrancoisOdendaal** [particl/partgui#158]
The "Next Step" buttons on all the following interfaces are misspelled as "Nexr Step":

Create new Wallet, step 2 onward (not an issue on the first step)
Restore Wallet, step 2 onward (not an issue on the first step)

![image](https://user-images.githubusercontent.com/32632469/31485449-2570ab7e-af34-11e7-9a67-c80ce7356748.png)

**Comment by FrancoisOdendaal** [comment]
This is on the develop branch

**Comment by kewde** [comment]
fixed in commit 824c489699ed1c9f24116947917ddbb425507577
