### ISSUE TITLE
Resize issue

### ISSUE THREAD

**Issue by kapsr** [particl/partgui#210]
Couple of resize issues in the latest build, see screenshots:

![resize1](https://user-images.githubusercontent.com/32437236/32138486-dfd96eb8-bc33-11e7-866e-8c67cf502413.jpg)
![resize2](https://user-images.githubusercontent.com/32437236/32138490-e2972c1c-bc33-11e7-96a1-569709cf12bb.png)
![resize3](https://user-images.githubusercontent.com/32437236/32138491-e51a25ca-bc33-11e7-94fc-b475ff5ab91d.png)
![resize4](https://user-images.githubusercontent.com/32437236/32138492-e7a6ca96-bc33-11e7-8576-37c038e1fb60.png)
![resize5](https://user-images.githubusercontent.com/32437236/32138493-e9c9a212-bc33-11e7-9c5d-bbf671e62edb.png)
![resize6](https://user-images.githubusercontent.com/32437236/32138494-ec13c7e6-bc33-11e7-89b8-d6539181dc17.png)

**Comment by allienworks** [comment]
Fixed.
