### ISSUE TITLE
Staking widget displays staking info despite staking being de-activated

### ISSUE THREAD

**Issue by kapsr** [particl/partgui#213]
I don't think this info should be visible/displayed when user is not staking. Maybe display a default "No coins are being staked at the moment" or something like this.

![stakeweightnextrewarddisplayedwithoutstake](https://user-images.githubusercontent.com/32437236/32138574-1b76145c-bc35-11e7-8e56-7d58f72ea1c8.jpg)

**Comment by allienworks** [comment]
Fixed.
