### ISSUE TITLE
Several UX issues on the Send payment/transfer balance pages

### ISSUE THREAD

**Issue by kapsr** [particl/partgui#215]
1: Spacing is far to wide, makes page less 'readable' from a UX point of view. Earlier official testnet build was much better designed. (Same problem on Send Payment page)

2: From Account / TO ACCOUNT: non capital and CAPITAL: Be consistent. 

3: I think there should be an indication somewhere in the text that this "note" is optional and not mandatory.

4: Background color of button "SHOW RECIPIENT ADDRESS" is different compared to the page itself. Same goes for "HIDE..." button.

![send](https://user-images.githubusercontent.com/32437236/32138671-0b8cce26-bc37-11e7-847b-c451513a3ee7.jpg)

**Comment by allienworks** [comment]
Fixed.
