### ISSUE TITLE
Failed TXs not announced

### ISSUE THREAD

**Issue by allienworks** [particl/partgui#216]
When trying to send TX with higher amount than you have, a small modal of "are you sure you want to send X to Y?" gets fired, but after confirming it, nothing happenes. Someone might interpret it as TX being sent, but it doesn't. Some modal about "you don't have sufficient PARTs for this TX" will help.

**Comment by HenkSwardt** [comment]
Logged task and assigned to Kirti

https://particl.atlassian.net/browse/PAR-244

**Comment by kewde** [comment]
Status? @anandsinghparihar

**Comment by anandsinghparihar** [comment]
No bug found ... its already working fine !!

**Comment by allienworks** [comment]
It's still there - https://imgur.com/a/yekJE
If you select all coins and try to send them the TX will fail (because you don't have anymore coins for TX fee), but nothing happens.

**Comment by allienworks** [comment]
OK, so apparently https://github.com/particl/partgui/pull/268/commits/840d3a4aa1ebc853fdd867d928e0dfe234c2c50f fixes this.

**Comment by dasource** [comment]
If you select "sendall" then the RPC command should set `subtractfeefromamount` as true.
This will then subtract the fee from the full amount.

**Comment by allienworks** [comment]
@dasource that might be true, but we don't have any "Send all" button in the GUI yet. Adding that to our TODO.

**Comment by pciavald** [comment]
should we close this issue as it was moved to a todo ?
