### ISSUE TITLE
Cosmetic Issues 

### ISSUE THREAD

**Issue by kapsr** [particl/partgui#259]
- [x] Stealth address in readable words, alignment issue
- [x] Stealth address hidden behind buttons
- [x] Address lookup - overflow of type
- [x] Other address lookup - overflow of stealth addresses
- [x] Alignment advanced options in receive tab

### Stealth address issues

1: Alignment
2: Can't manually copy full address by selecting it, cut off from screen. Only with copy button. I think address needs to be manually selectable also.

![addressalignment](https://user-images.githubusercontent.com/32437236/32409077-fd236034-c1a4-11e7-86f9-5bfa5862d498.jpg)

### Address lookup - overflow of type

![addrrsslookup](https://user-images.githubusercontent.com/32437236/32409087-2d073fdc-c1a5-11e7-85dd-40509e1f5c97.jpg)

### Other address lookup - overflow of stealth addresses
![privateaddressalignment](https://user-images.githubusercontent.com/32437236/32409088-327d1e8c-c1a5-11e7-8c46-3101cf3351f2.png)

### Alignment advanced options in receive tab
![allignmentshowhidebutton](https://user-images.githubusercontent.com/32437236/32409091-4dbe50c6-c1a5-11e7-90c1-dacb65bbc345.jpg)

I think you want to align these buttons (left) instead of right, less visual annoyance when clicked.

**Comment by kewde** [comment]
Would be easier to keep track of if these were separate issues

**Comment by kapsr** [comment]
Sorry, i thought i could merge these mere 'minor' issues. Will create separate issues on further tests, if i am able to find more.

**Comment by kewde** [comment]
Thanks for the testing tho, really appreciate it.
I'm making some changes to your initial post.

**Comment by kewde** [comment]
Also, why is your particl logo missing from the UI?

**Comment by kapsr** [comment]
looks good. There is no logo apparently anymore when compiling dev. branch.

**Comment by kewde** [comment]
@kapsr works fine here..

Are you compiling to binaries or running with `npm run start:electron`?

**Comment by kapsr** [comment]
@kewde npm run start:electron

**Comment by allienworks** [comment]
**1) Stealth address in readable words, alignment issue**
- yes, this could be done better, we'll come up with something

**2) Stealth address hidden behind buttons**
- they are too long for the space obviously; they are snipped, but if you double-click the address and copy it, you will have the whole addy in your clipboard.
- you can also select the address via button and copy it manually from the detail box on the left
- other than that, there's the copy button, which IMO suffices

**3) Address lookup - overflow of type** &
**4) Other address lookup - overflow of stealth addresses** &
**5) Alignment advanced options in receive tab**
- _fixed already_
