### ISSUE TITLE
Particl icon background not transparent anymore

### ISSUE THREAD

**Issue by kapsr** [particl/partgui#281]
![13834eded5331824d7c3b8d13bae3706](https://user-images.githubusercontent.com/32437236/32572077-cc472e6e-c4c9-11e7-9a92-f1f242fc9be4.png)
![c68e7b8d10608a53626655f225b6594e](https://user-images.githubusercontent.com/32437236/32572082-ce0e001a-c4c9-11e7-8439-cd472822653d.png)
![t](https://user-images.githubusercontent.com/32437236/32572220-3a5c76f2-c4ca-11e7-842f-34012f52d75a.png)

Also: Main logo is still missing when i compile develop branch, not sure why

**Comment by kewde** [comment]
#270
