### ISSUE TITLE
after update, -reindex flag not working automatically

### ISSUE THREAD

**Issue by kapsr** [particl/partgui#313]
blockchain is not stored.

**Comment by rynomster** [comment]
Blockchain is stored. If you disconnect your network you'll see it still
syncs.
It seems like an indexing issue one some machines. We'll have to do a bit
more work on it, just to make sure the daemon is ending gracefully on
windows.

**Comment by pciavald** [comment]
Probably fixed by #455. Please reopen if it's not fixed after Wallet 1.1.0 release.
