### ISSUE TITLE
Double-click on window title doesn't go fullscreen

### ISSUE THREAD

**Issue by Diti** [particl/partgui#316]
On Windows 10 and macOS, double-clicking on a window title should make the window go fullscreen.
The new Particl wallet doesn't have this behavior.

**Comment by kewde** [comment]
Resizing not allowed for the moment.

**Comment by HenkSwardt** [comment]
This will be part of one of or later versions. We need to ensure resizing on all pages keep look feel and behavior in place. Closing this issue in favor of task logged for this enhancement.
