### ISSUE TITLE
Force to create new address if clicking receive(public) for the first time 

### ISSUE THREAD

**Issue by SativaL** [particl/partgui#320]
https://giphy.com/gifs/3ohs7WrhJ9Z4P0ocTu/fullscreen

if you come from the enter page to the "Receive" tab for the first time, sadly the wallet doesnt ask you to create a first public address, only if you click private (then it ask you for private) and then if you go back to public it will ask you :)

**Comment by allienworks** [comment]
This issue should be fixed already.

- What OS are you running? Linux x64?
- Did you create a new wallet or restored an existing one?
- Do you use `particl.conf`?

**Comment by kewde** [comment]
Did you import the wallet with the GUI wallet or through Qt?

**Comment by SativaL** [comment]
qt, guess its then fixed like you said with again importing mnemonic
