### ISSUE TITLE
reverse receive and send arrows

### ISSUE THREAD

**Issue by SativaL** [particl/partgui#321]
i think it is better to have the send arrow heading towards the right side and the receive arrow heading towards the left side.

Personally i would also put the "Send" tab first and after that the "Receive" tab, thats just "standard" most likely i guess, which we can also see in QT clients all over the place.

**Comment by LiteBit** [comment]
What about making "Send" arrow going up and "Receive" arrow going down?

**Comment by SativaL** [comment]
No, i think standards within software development is what i have said above.

**Comment by allienworks** [comment]
It originally was the other way around, my logic was that depends which way the arrow points from the text:
```
=> Receive
<= Send
```
is IMO therefore better than
```
<= Receive
=> Send
```
because in Receive the arrow points away.

If we'd move the icons to the right, I'd agree with you again (as the Send's arrow would point away):
```
Receive <=
Send =>
```
but this is not the case.

Completely my opinion though, let's have a discussion.

**Comment by kapsr** [comment]
i agree with Satival

**Comment by kapsr** [comment]
I think symbols should have meaning independent of what information is surrounding them, so i think the argument by allienworks (if send or receive are placed in front or behind the symbol) is not a valid argument (although i understand what you are saying)

**Comment by LiteBit** [comment]
What if it was something more like these?
![send_receive-01](https://user-images.githubusercontent.com/6236019/32702866-1f543e32-c7bb-11e7-9660-7464b0957156.png)
![send_receive-02](https://user-images.githubusercontent.com/6236019/32702867-1f618146-c7bb-11e7-9b52-a0cd72d510f3.png)

**Comment by kapsr** [comment]
i like em litebit

**Comment by HenkSwardt** [comment]
We will goi with suggestion from @LiteBit . @gerlofvanek will give us the official Particl branded version shortly.

**Comment by LiteBit** [comment]
I noticed [Exodus Movement](http://www.exodus.io/#design) has something similar for In and Out.

![capture](https://user-images.githubusercontent.com/6236019/32744382-4e857a8c-c87d-11e7-99f4-ee03ddb8eddc.PNG)

**Comment by SativaL** [comment]
i dont like them, really like the classic one in correct standard layout most.

**Comment by gerlofvanek** [comment]
#453
