### ISSUE TITLE
osx menu should have a fixed width

### ISSUE THREAD

**Issue by LoneWolf367** [particl/partgui#323]
The menu bar icon needs to be scaled down. Currently it's about 1/4 the width of my entire menu bar.

OS X Version: 10.12.6
Particl Wallet: v1.0.0

![screen shot 2017-11-10 at 10 03 04 am](https://user-images.githubusercontent.com/171644/32672051-92c5f40a-c5fe-11e7-84f4-804aa22c3719.png)

**Comment by HenkSwardt** [comment]
Standardise Tray / taskbar behaviour #363 

Closing this task
