### ISSUE TITLE
Overview Screen: Staking Information Modal

### ISSUE THREAD

**Issue by LiteBit** [particl/partgui#324]
The "%" text in the Staking Information modal has an extra "o" in the "Your stake weight" row.
![image](https://user-images.githubusercontent.com/6236019/32674474-64426a46-c621-11e7-8be8-30870a026271.png)

**Comment by LiteBit** [comment]
Minor Visual Issue

**Comment by allienworks** [comment]
Yes. It's not a bug, it's a feature!

And it's not percent, it's [per mille](https://en.wikipedia.org/wiki/Per_mille) (= 1/1000th of the whole). But there are more ppl confused, so I guess we should switch to more common percents instead.

**Comment by LiteBit** [comment]
Oh I see. Wasn't aware of per mille :) 
I think it should stay.
