### ISSUE TITLE
Wrong version number in task bar

### ISSUE THREAD

**Issue by imybb** [particl/partgui#327]
Wrong version number is the task bar
![tray_icon_wrong_version](https://user-images.githubusercontent.com/30150617/32688563-2ecfce3a-c6cb-11e7-993f-f0e679d71e92.png)

If I'm right this should read Particl Wallet 1.0.0

**Comment by rynomster** [comment]
Is this the build that you downloaded from our github release?

**Comment by imybb** [comment]
no, I think it's the one you sent a link to as we was pre-testing

**Comment by imybb** [comment]
I'll download the one from github and try that

**Comment by imybb** [comment]
Internal release was wrong, github release shows Particl 1.0.0

**Comment by rynomster** [comment]
Yeah because we were still testing :)
