### ISSUE TITLE
History first and last page access buttons

### ISSUE THREAD

**Issue by imybb** [particl/partgui#328]
*enhancement*

Can we please add a First Page - Last Page in the history tab, once you click through to the end you have to click your way back to first page.

Could we also add the same at the top of the history section, this will save having to scroll down page every time in order to go to next or previous page.

Thanks

**Comment by HenkSwardt** [comment]
Fr this issue we will need to write our own "First and Last page" as its not a sported or supplied feature. 

Please see https://github.com/angular/material2/issues/6665 for details.

Closing comment of above isssue on Material2 branch:

> Our paginator is based on the Material Design spec, which doesn't have the extra buttons.We generally expect that people will mostly make a custom paginator specific to their apps (since there is actually no coupling between the table, data source, or the paginator).

**Comment by HenkSwardt** [comment]
@EagleEye25 will be looking into this for us.

**Comment by anandsinghparihar** [comment]
@HenkSwardt We will go with custom component I'll do it.

**Comment by anandsinghparihar** [comment]
PR: https://github.com/particl/partgui/pull/460
