### ISSUE TITLE
can't paste address in "Add new address to Address book" (osx)

### ISSUE THREAD

**Issue by sebpalluel** [particl/partgui#332]
![issue paste address](https://user-images.githubusercontent.com/11297176/32689362-5f882442-c6e3-11e7-9c4e-391c337bf310.jpeg)

**Comment by rynomster** [comment]
Try cmd+v

**Comment by rynomster** [comment]
We'll have to add some basic context menus I guess :)

**Comment by sebpalluel** [comment]
It's not working either with cmd + v or right click, paste. Don't want to mess up by writing it down char by char ;). Maybe the easier way would be to be able to paste it directly into the page. In the same way as in "WebTorrent" you can paste directly the hash of a torrent and it's added automatically.

**Comment by anandsinghparihar** [comment]
Right click is not working in electron & I test in 2 different mac cmd+v is working fine.

I'll be adding paste button so if a user wants to paste address so he can use paste button or cmd+v.

**Comment by pciavald** [comment]
@gerlofvanek i think there's a comment for you in that commit ^

**Comment by HenkSwardt** [comment]
PR awiting review for this issue #339

**Comment by pciavald** [comment]
solved
