### ISSUE TITLE
only 24 words seeds are allowed - allow 12, 15 and 18 words too

### ISSUE THREAD

**Issue by SativaL** [particl/partgui#333]
a mnemonic seed with less than 24 words cant be important into the new gui. (tried with 18 words from the standalone particl generator)

The "Next" button stays grey and does nothing.

**Comment by rynomster** [comment]
Thanks, this is a valid bug.. I also have some 12 and 15 word mnemonics
lying around

**Comment by pciavald** [comment]
moved to PR
