### ISSUE TITLE
uncaught exception: could not connect to daemon

### ISSUE THREAD

**Issue by ArMuta** [particl/partgui#343]
<img width="532" alt="screen shot 2017-11-13 at 16 06 42" src="https://user-images.githubusercontent.com/33633278/32747192-42513694-c8b8-11e7-8fbe-113d708694bf.png">

# Describe bug/issue
Cannot launch wallet anymore

# How to reproduce
Laptop went on sleep, as the system went out of sleep, Wallet displayed a connection issue, then closed, then seems unable to re-launch.

# More information

- Operating system and version: Mac OS Sierra 10.12.6
- Client version: 1.0.0

**Comment by pciavald** [comment]
my guess is that it comes from here : 
https://github.com/particl/partgui/blob/master/modules/rpc/daemon.js#L169
if so it would be fixed by merging #297 
https://github.com/pciavald/partgui/blob/d6af290db95cb510afb946cdca51177d11beb0b4/modules/init.js#L33

**Comment by pciavald** [comment]
@ArMuta problem should disappear with a reboot

**Comment by HenkSwardt** [comment]
Hi @pciavald 

#297 has been merged to Dev branch, can you please test and confirm that this has been resolved.

Thanks

**Comment by pciavald** [comment]
This should be fixed by #455. Please reopen if not when we release Wallet 1.1.0
