### ISSUE TITLE
redefine logging levels

### ISSUE THREAD

**Issue by pciavald** [particl/partgui#344]
We should have precise logging levels for the backend, that also logs the front. It will help debug the users' issues.

https://www.npmjs.com/package/electron-log

**Comment by HenkSwardt** [comment]
Hi @pciavald 

Please confirm that this is now in place following the merge of #297 

Thanks

**Comment by allienworks** [comment]
This has been solved already, right @pciavald?

**Comment by pciavald** [comment]
sorry, nope it's not solved yet :)

**Comment by pciavald** [comment]
moving to PR
