### ISSUE TITLE
Number of confirmations doesn't update in "Overview" tab

### ISSUE THREAD

**Issue by cryptoguard** [particl/partgui#345]
The number of confirmations displayed in each transaction lines in "Overview" (i.e. 12+) doesn't update if staying on the same page. The number of confirmations is updated when switching sections by clicking on another tab (i.e. Send) and then clicking back on "Overview". 

Is this on purpose? It would feel better if it updated in real-time especially for monitoring staking rewards and their confirmations.
![selection_004](https://user-images.githubusercontent.com/27031337/32763392-6cd5fc46-c8cd-11e7-8792-11f5ec58553a.jpg)

**Comment by pciavald** [comment]
closing for PR
