### ISSUE TITLE
Add more "Items per page" in History section

### ISSUE THREAD

**Issue by cryptoguard** [particl/partgui#346]
Currently, it is only possible to choose between 5, 10 and 20 transactions displayed per pages. Could more options be added like 50, 100, 250, etc. 

This is easier to have many transactions on the same page when monitoring staking rewards and also to quickly search for a specific transaction. Easier to scroll than have to click the next arrow for hundreds of pages. 

Alternatively, a page menu dropdown could be added to quickly jump through a lot of pages. 
![selection_005](https://user-images.githubusercontent.com/27031337/32763502-16218e5a-c8ce-11e7-9997-afbe8df5f75d.jpg)

**Comment by allienworks** [comment]
I believe this is solved already and will be included in the next release.
