### ISSUE TITLE
Cannot make a balance transfer from blind to public

### ISSUE THREAD

**Issue by cryptoguard** [particl/partgui#347]
It is possible to make a balance transfer from a public address to a blinded balance, however it does not work the other way. Radio buttons are greyed out and cannot be changed. Unsure if it is on purpose.

NOTE: In this screenshot, I do have a public (X PARTs) 
![selection_006](https://user-images.githubusercontent.com/27031337/32763761-a4ed1ea0-c8cf-11e7-8c35-f347004fd773.jpg)
and private balance (1 PART).

**Comment by vikas-cis** [comment]
#360

**Comment by HenkSwardt** [comment]
Changes has been merged to Dev. Closing issue
