### ISSUE TITLE
Gracefully shutting the deamon on Windows

### ISSUE THREAD

**Issue by HenkSwardt** [particl/partgui#351]
We need to look at a way to allow a graceful shut down of deamon on Windows
- Operating system and version: Windows

**Comment by pciavald** [comment]
should be fixed by #297

**Comment by HenkSwardt** [comment]
We have merged #297 to Dev branch. Can this please be tested and confirmed to have been resolved.

@kewde will you please check this for us.

Thank you

**Comment by pciavald** [comment]
@HenkSwardt @anandsinghparihar is this still an issue ?
