### ISSUE TITLE
Warn/inform user if wallet is running on testnet

### ISSUE THREAD

**Issue by HenkSwardt** [particl/partgui#353]
Display some "warning" when you're running wallet on testnet + change main sidebar logo (main sidebar logo + small subtext “testnet”) in red if on testnet

**Comment by gerlofvanek** [comment]
I will make the testnet logo + upload the testnet logo.

**Comment by rynomster** [comment]
We can also add - testnet to the title

**Comment by gerlofvanek** [comment]
#453

**Comment by gerlofvanek** [comment]
@pciavald 
If testnet replace sidebar logo particl-logo.svg -> particl-logo-testnet.svg
If testnet add "- testnet" in application title

**Comment by pciavald** [comment]
is this complete already @gerlofvanek ? Or is there something missing ?
