### ISSUE TITLE
generate API documentation

### ISSUE THREAD

**Issue by pciavald** [particl/partgui#355]
We should write a script to generate documentation from RPC API functions. This way we can regenerate the documentation without having to manually checkout API changes and additions.

**Comment by HenkSwardt** [comment]
Hi @pciavald , 

Jason (@EagleEye25 ) will take a stab at this for us. 

Thanks

**Comment by pciavald** [comment]
I think @EagleEye25 is not in the list of this repo because I cannot assign him @HenkSwardt

**Comment by pciavald** [comment]
[Bitcoin API list example](https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list)
[RPC function example](https://github.com/particl/particl-core/blob/master/src/wallet/rpchdwallet.cpp#L3054)

**Comment by HenkSwardt** [comment]
Issue has been completed in https://github.com/particl/partgui/pull/383

**Comment by pciavald** [comment]
This task is in its minimum state and IMO should be enhanced.
