### ISSUE TITLE
Cant decrypt wallet (not even restore, angular gui)

### ISSUE THREAD

**Issue by SativaL** [particl/partgui#361]
Hey, tried to enter my passphrase (completely right copied) to decrypt my angular wallet.. but it said 

Unlock failed - password was incorrect Dismiss

even the password was 100% right, no additional space i checked, also the password works without problem in qt client.

also i even tried to restore fully with always deleting .particl folder, so after entering my mnemonic key and passphrase (correctly copied and without spaces) it said "parse error".. cant access my coins through the angular gui ?! importing works perfect with qt ..

**Comment by SativaL** [comment]
ps: when i create a new seed with the new wallet, i can import it. but when i try to import the old seed, doesnt work. PARSE ERROR

**Comment by HenkSwardt** [comment]
I have asked @EagleEye25 to investigate this issue for us and add additional test cases where needed.

**Comment by EagleEye25** [comment]
I have created a test wallet, and deleted the wallet.dat from particl, for wallet restore purposes and have recieved no issue with restoring the wallet, also with the current error validations that ive added https://github.com/particl/partgui/pull/418, if wrong words have been entered it will now display an error. We are not able to write tests for the restore wallet as of now, as the tests do not start the daemon.

**Comment by pciavald** [comment]
should be fixed by 433, please reopen after release 1.1 if the problem persists
