### ISSUE TITLE
Create wallet modal misaligned - sync bar misaligned - sidebar error message

### ISSUE THREAD

**Issue by HenkSwardt** [particl/partgui#376]
When Creating a new wallet on OSX we have misalignment on the first modal. Please see screenshot below:

![image-10310](https://user-images.githubusercontent.com/28799964/32946813-b944f330-cba1-11e7-93cf-93f43d109012.jpg)

- Operating system and version: Latest OSX
- Client version: GUI Dev

**Comment by anandsinghparihar** [comment]
@allienworks could you please check it, I tried to resolve it but I guess flex is not working properly here 
![Uploading Screen Shot 2017-11-29 at 2.12.42 PM.png…]()
![screen shot 2017-11-29 at 2 12 57 pm](https://user-images.githubusercontent.com/17725557/33370128-a63dab5e-d51c-11e7-8131-d6a40daaafb8.png)

**Comment by gerlofvanek** [comment]
@anandsinghparihar Bug same on windows (restructure branch). 

After deleting the wallet.dat and restarting the client. 

![Image of windows wallet](https://i.gyazo.com/b9a0466a71ab0558f12b6bfa66d9ee07.png)

(Other thing I noticed - sync bar not looking ok on restructure branch)

**Comment by anandsinghparihar** [comment]
Yeah, issue is really strange... flex should be work in all operating system

**Comment by allienworks** [comment]
There's another issue. Wallet seems not to be recognizing if `wallet.dat` is present, because in your sidebar, there are both "Wallet" sections (the one for when `wallet.dat` isn't present AKA "Add account" menu + the other when `wallet.dat` is present AKA "Receive / Send etc."

**Comment by pciavald** [comment]
@HenkSwardt @gerlofvanek @anandsinghparihar does this issue still exist ?

**Comment by anandsinghparihar** [comment]
@pciavaldI cant see it in Linux since its mac issue @gerlofvanek is checking it
