### ISSUE TITLE
Sync modal (empty) still firing up when syncing

### ISSUE THREAD

**Issue by allienworks** [particl/partgui#381]
When launched and blockchain isn't synced, the syncing modal (see https://github.com/particl/partgui/pull/356) still fires up, even though it's empty.

We need not to launch the modal at all, syncing process is shown in the sidebar menu now.

(`develop` branch)

**Comment by kewde** [comment]
It shouldn't be empty tho, it's only empty when loading?

**Comment by allienworks** [comment]
Hmm, looks like a misunderstanding. I thought we'll get rid of the whole syncing modal (and replace it by the progressbar in sidebar instead). If needed, we can add all those other infos to the progressbar as well (like remaining blocks, ETA etc.)..

**Comment by pciavald** [comment]
closing in regard to the PR
