### ISSUE TITLE
Encryption  modal is not closed  after setup encryption key 

### ISSUE THREAD

**Issue by anandsinghparihar** [particl/partgui#393]
Encryption modal is not closed, initially if a user created wallet without setup encryption key, After that user, just setup Encryption key then Encryption Modal would be closed, but it's not closed. 

_As per default functionality after setup encryption key user will redirect to create wallet page._

**Comment by anandsinghparihar** [comment]
Some time unlock modal is also auto closed !!

**Comment by anandsinghparihar** [comment]
@pciavald could please help me to find out why the demon is not restarted if no wallet created or while user setup encryption key.

**Comment by pciavald** [comment]
Yes I'll check that up tomorrow.

**Comment by pciavald** [comment]
I've just noticed that when the wallet is unlocked, and we click on the lock button, the UNLOCK modal pops up. Should not. Can you fix it please ?

**Comment by anandsinghparihar** [comment]
Yes I'll thanks

**Comment by vikas-cis** [comment]
I was running the restructure branch and get a wired issue while opening the unlock modal, it automatically gets closed 

OS: Windows 7

**Comment by anandsinghparihar** [comment]
@pciavald 
>I've just noticed that when the wallet is unlocked, and we click on the lock button, the UNLOCK modal pops up. Should not. Can you fix it please ?

>>>>>>>>>>>(if no wallet and encryption key setup) Yeah if we click on lock button then UNLOCK modal is poup for setup encryption key, I guess no problem with that unlock modal.

**Comment by pciavald** [comment]
i had a problem that seems not to exist anymore. Should be fixed by #455 for the creation modal that doesn't close, it was due to the daemon not restarting correctly.
