### ISSUE TITLE
Missing css file

### ISSUE THREAD

**Issue by EagleEye25** [particl/partgui#437]
# Describe bug/issue
`overview:7 GET http://localhost:4200/assets/index.css `

It seems as if its been changed to scss, without adding the ability for the index.html file to be able to read the scss..
..

# How to reproduce

1. Run application
2. Open debug console

# More information

- Operating system and version: windows
- Client version: resrtructure branch

**Comment by allienworks** [comment]
Fixed in https://github.com/particl/partgui/commit/a2f8f4cc796b9e92e5a3037ff41f79b1a8140c7e
