### ISSUE TITLE
Addition of CSS classes to confirmations

### ISSUE THREAD

**Issue by HenkSwardt** [particl/partgui#452]
Add different CSS classes to confirmations, based on # of them.

e.g.:
​​0 confirmations = `.confirm-none`
​​1-4 = `.confirm-1` 
​​5-8 = `.confirm-2`
​​9-12 = `.confirm-3`
​​12+ = `.confirm-ok`

@allienworks , once Vikas has done this he will hand over to you for #GFX portion

**Comment by allienworks** [comment]
Merged.
