### ISSUE TITLE
No gpg signature for wallet download.

### ISSUE THREAD

**Issue by peterhendrick** [particl/partgui#457]
No gpg signature for downloads or shasums.

Seems like a pretty easy step to add in. It's pretty standard practice. Ensures that your download has been signed by the authors and has been uncorrupted since being signed.

**Comment by SativaL** [comment]
https://github.com/particl/partgui/releases/tag/v1.0.0

4b5554b3b334bc621bcb30537e8102636b7673175f6a3af2972c8435f59e5617  particl_1.0.0_amd64.deb
f2487f8bcc78dabeeac00a19b97db047cc5304486c432a50449cb65d43a875b3  particl-1.0.0-linux.tar.gz
e4bfe480e23f8c59d642f00933de16ebc511dae02638ab2a37b95565031ec87b  particl-1.0.0-mac.zip
75348e85f03a822b5ca24d20c2ce050bd4d082e31fd94492498db1afcc384cc4  particl-1.0.0-setup-win64.exe
d0bdec34e7cdd16ea84678b851fdb0f37dbd4cb3072e1f2126723e73edb83f29  particl-1.0.0-win64.zip


what you mean ?

**Comment by kewde** [comment]
@peterhendrick

We do gitian-builds for particl-core. You can build yourself and verify that it was built correctly.
We do not provide gitian-builds for our GUI, but it is something we're looking into.
The node dependencies aren't pinned so we can't do deterministic builds yet.
