### ISSUE TITLE
OSX version can't paste password for staking

### ISSUE THREAD

**Issue by ChurchOfNotNothing** [particl/partgui#459]
# Allow for pasting password to stake

I can't tell you how annoying it is to have to type in my password which is complicated. 
..

# I Personally would settle for the ability to command + v or even a right click with option to paste

- Operating system and version: High-Sierra OSX 10.13.1

**Comment by HenkSwardt** [comment]
Hi @ChurchOfNotNothing 

We have tested this in the current Dev build as some pasting issues were addressed and it seems to be working now. Please note it will be available in the next release.

Thank you for logging.
