### ISSUE TITLE
Addition of Help Text or Tooltips to GUI

### ISSUE THREAD

**Issue by HenkSwardt** [particl/partgui#461]
We need to add tooltips to the GUI in places that might need explaining or guidance. 

This feature will be to assist the user navigate the GUI.

Assigning task to @EagleEye25

**Comment by EagleEye25** [comment]
added tool tips on overview, receive, send, history, address book, to help users navigate through out the app. go to https://docs.google.com/document/d/17897eXtgw7tk4rUpGTYt8S6yImygRetZBsvzGa6iioA/edit for more information
