### ISSUE TITLE
Debug Console Log

### ISSUE THREAD

**Issue by vikas-cis** [particl/partgui#469]
Debug window functionality similar like in QT wallet

**Comment by vikas-cis** [comment]
![screenshot](https://user-images.githubusercontent.com/20254889/33673120-f7a2908a-dad1-11e7-9964-a053ed5b50d9.png)

@gerlofvanek : Need this icons to be change :)

**Comment by vikas-cis** [comment]
![screen shot 2017-12-07 at 9 24 17 pm](https://user-images.githubusercontent.com/20254889/33724289-0e6d404e-db95-11e7-81ee-93ad55cd6c77.png)

@gerlofvanek I have added the dummy icon at the top right over status, we need to replace with the one you will create :)

Thanks

**Comment by anandsinghparihar** [comment]
PR: https://github.com/particl/partgui/pull/470
