### ISSUE TITLE
Incorrect password when encrypting on restore wallet overwrites original password

### ISSUE THREAD

**Issue by HenkSwardt** [particl/partgui#485]
This issue was reported to me via a message, @anandsinghparihar is busy investigatiing if it is possible to reproduce and test this functionality. 

1. Changing password, says it is incorrect but keeps the newly entered password.
2. The wallet is encrypted and locked but the icon shows unlocked

# How to reproduce

1. While restoring a wallet and at the encrypt step you entered a different password (Not your saved password). The correct error was produced stating that encryption failed. However it seems that the password were overwritten with this new one as it was the one  In this case it over wrote his old password. Im asking that was used to unlock the wallet for staking. The older, original password did not work anymore. 
2. Following above from point one, if the wallet is locked the icon shows as unlocked. 

# More information

**A summary of above issue: GUI correctly shows error for incorrect password but still accepting and changing it then shows unlocked even when locked**

- Operating system and version: Win 10 Pro
- Client version: MainNet 1.0

**Comment by anandsinghparihar** [comment]
I restored my wallet 
> name:  Kiriti Des
Pass: test123
title paddle oblige random orange vanish happy gloom cradle monkey weather garage bottom disease toward require tiny capable build scare else approve feel laugh

after successfully restore wallet, I just setup wallet encryption key but its not set. please check this console log : https://gist.github.com/anandsinghparihar/bcc92018f2cc50bd02d47ca8e07fd91e

![screenshot from 2017-12-08 17-52-55](https://user-images.githubusercontent.com/17725557/33766161-49a2b68c-dc42-11e7-9ac5-6f77268728f3.png)

**Comment by vikas-cis** [comment]
#511

**Comment by anandsinghparihar** [comment]
I've test restart demon issue has been fixed in this PR: https://github.com/particl/partgui/pull/511#pullrequestreview-84102186

Other things maybe I need to discuss with @HenkSwardt, what is password change?

**Comment by HenkSwardt** [comment]
Hi @anandsinghparihar 

In this scenario, it is when entering a different password to the one you were suppose to. That over writes the original one for some reason and wants to make use of it for future.

**Comment by anandsinghparihar** [comment]
all working fine : https://github.com/particl/partgui/pull/511#pullrequestreview-84102186
