### ISSUE TITLE
Notifications for new wallet updates available

### ISSUE THREAD

**Issue by LiteBit** [particl/partgui#488]
# Users don't know if Particl Wallet has been upgraded without checking Github

Once a user downloads Particl Wallet they should no longer need to ever go to Github to get another version. 
* "Upgrade to latest Particl Wallet v.### available"
-- 2 buttons for choices (**upgrade now**) (**remind me later**)

The wallet is coded to automatically grab the latest daemon release. The same convenience needs to be given to upgrading GUI.

**Comment by pciavald** [comment]
this will be implemented for manual download in 1.1.0 (#493) and automatic download and install in 1.2.0 (#593)
