### ISSUE TITLE
Narrations disappeared

### ISSUE THREAD

**Issue by allienworks** [particl/partgui#496]
Narrations were already done and working, merged to `develop` (https://github.com/particl/partgui/pull/357). Now on `dev` (and even on `restructure`), the narrations aren't working anymore.

I've checked if the changes from https://github.com/particl/partgui/pull/357 are included and yes, they are there. Probably some logic changed during restructure and that might broke it.

So we need the narrations to display again.

**Comment by pciavald** [comment]
@anandsinghparihar is there a PR for that ? I thought you were done with it except for internal_transfers, and I need it to test the search functionnality in the filters.

**Comment by anandsinghparihar** [comment]
@pciavald Yes this task is in progress when I done I'll share PR here

**Comment by anandsinghparihar** [comment]
PR: https://github.com/particl/partgui/pull/520
