### ISSUE TITLE
Failed to open new connection, already connected

### ISSUE THREAD

**Issue by anandsinghparihar** [particl/partgui#498]
If we created wallet without setup encryption key wallet is created successfully without encryption checks because initially wallet is unlocked. 

and then if user setup encryption key then it's by default redirect to create wallet step which is already done. and its again restart demon failed.

could you please clear following points
1. Is create/restore wallet can be done without encryption key check is that inflow? 
2. I guess only set encryption button would enable the first time (disable other button like create or restore wallet )?

Console log: https://gist.github.com/anandsinghparihar/f9c2018caa267b65e8b61f93c7bf65a4

**Comment by vikas-cis** [comment]
#511

**Comment by anandsinghparihar** [comment]
fixed in this PR: https://github.com/particl/partgui/pull/511#pullrequestreview-84102186
