### ISSUE TITLE
transactions flash every 30s

### ISSUE THREAD

**Issue by pciavald** [particl/partgui#499]
The transaction service fetches for new transactions every 30s on top of fetching the transactions when tx count has changed. Is it necessary ?

This interval update causes Material to reload the list and displaying an adjustment animation from left to right.

https://github.com/particl/partgui/blob/dev/src/app/wallet/wallet/shared/transaction.service.ts#L54

**Comment by pciavald** [comment]
It also closes opened transactions

**Comment by HenkSwardt** [comment]
@kewde Can you please have a look at this for us. I believe you assisted with this in the past.

Thanks

**Comment by pciavald** [comment]
#563
