### ISSUE TITLE
Locking wallet stops Cold Staking activation

### ISSUE THREAD

**Issue by HenkSwardt** [particl/partgui#512]
Cold Staking and Locked Wallet

If Cold Staking is enabled and the wallet is "locked" the cold staking "activation" process stops.

Therefore if the Cold Staking Activation % is < 100% and Wallet = locked, the Cold Staking widget should advise the user "to unlock the wallet for staking to continue the Cold Staking Activation"

**Comment by HenkSwardt** [comment]
@EagleEye25 will have a look at this for us.

**Comment by EagleEye25** [comment]
implemented changes https://github.com/particl/partgui/pull/521

**Comment by anandsinghparihar** [comment]
PR: https://github.com/particl/partgui/pull/521
