### ISSUE TITLE
Password Validations and Acknowledgement step in Create Wallet.

### ISSUE THREAD

**Issue by HenkSwardt** [particl/partgui#524]
We highlighted a possible loophole where if one enters their Passphrase or Password during wallet creation and unknowingly miss-typed a character we have no way of validating this at the moment. 

Can we add a confirmation step after every "Create Password" step in the flow. This will allow a user to type in the password a second time and assist with finger troubles.

We also need to highlight the importance of keeping the information safe a bit more. Please look at the flow when creating a wallet on the Particl Copay app and add those acknowledgements.

**Comment by HenkSwardt** [comment]
@EagleEye25 will be looking into this for us.

Please consult with @dasource for review.

**Comment by HenkSwardt** [comment]
https://github.com/particl/partgui/pull/528

**Comment by anandsinghparihar** [comment]
PR: https://github.com/particl/partgui/pull/528
