### ISSUE TITLE
Fill in missings words bug

### ISSUE THREAD

**Issue by EagleEye25** [particl/partgui#527]
# Describe bug/issue
Once the user has click next until the fill in words phase on create wallet, and then suddenly decides to go back to the set optional password phase "step 2" then wants to proceed by clicking next, this bypasses the regeneration of 24 words, and takes the user straight to the fill words screen, with all the words being filled already, without the user having to fill them.
..
# How to reproduce
1. Run app without wallet
2. Proceed with create wallet
3. Go through steps in order to get to fill in missing words screen
4. Click "Back" untill password creation screen
5. Click "Next"

# More information
- Operating system and version: Windows 7 x64
- Client version: 1.1.0

**Comment by EagleEye25** [comment]
also, when entering without a password, instead of showing the intially 24 generated words, takes you to the fill in words page, without having to fill in the words.

**Comment by EagleEye25** [comment]
![ss 2017-12-19 at 03 18 28](https://user-images.githubusercontent.com/28861857/34158897-ebbadd24-e4cf-11e7-9840-9a52b1a7bd14.png)
![ss 2017-12-19 at 03 18 36](https://user-images.githubusercontent.com/28861857/34158898-ec79020e-e4cf-11e7-8425-2a748668e30f.png)

**Comment by EagleEye25** [comment]
seems to be working fine on current dev branch

**Comment by vikas-cis** [comment]
@HenkSwardt as discussed with @EagleEye25 dev is working fine :)

**Comment by EagleEye25** [comment]
was happening because of changed made in https://github.com/particl/partgui/pull/528 but have been fixed now, and working perfectly
this can be closed.
