### ISSUE TITLE
GFX problems in create wallet modal

### ISSUE THREAD

**Issue by pciavald** [particl/partgui#546]
to reproduce : delete wallet.dat and launch

- button has a grey square
- icons are off
- loading bar at bottom (should be removed ?) has rounded sides

![screenshot_20171222_213727](https://user-images.githubusercontent.com/3384097/34311912-cdc873b0-e760-11e7-9c63-b3a406a9426e.png)

![screenshot_20171222_213904](https://user-images.githubusercontent.com/3384097/34311875-9a89fa64-e760-11e7-9eb5-f272cac5db29.png)

**Comment by vikas-cis** [comment]
yeah I have also tested the stuff and seems the content moving left as well.
![screen shot 2017-12-25 at 4 11 19 pm](https://user-images.githubusercontent.com/20254889/34338395-53ddc318-e98e-11e7-900a-75ecbf4637b0.png)
