### ISSUE TITLE
GFX problem in cold staking setup modal

### ISSUE THREAD

**Issue by pciavald** [particl/partgui#547]
![peek 22-12-2017 22-01](https://user-images.githubusercontent.com/3384097/34312418-533fc5f4-e764-11e7-86b7-89a956c1c13a.gif)

**Comment by vikas-cis** [comment]
@pciavald I have tested the stuff over OSX and also in @anandsinghparihar (linux ubuntu) machine, seems working fine for both of us,  Can you tell us which machine have you tested this ?
Thanks

**Comment by vikas-cis** [comment]
@pciavald after deep checking I got the below scenario
1)Delete the wallet.dat
2)Restart process
3)Click on Cold Staking node and then I saw the issue that mention above

**Comment by pciavald** [comment]
@vikas-cis 
![screenshot_20171227_164937](https://user-images.githubusercontent.com/3384097/34385882-152af7be-eb26-11e7-8b17-ece1568b07fb.png)

**Comment by vikas-cis** [comment]
@pciavald yes I have mention this things are doing almost all the modals #546

**Comment by allienworks** [comment]
I've just tried to check this on https://github.com/particl/partgui/pull/526/ branch (which is latest `dev` + some more tweaks) and the issue seems to be resolved there. Let's see after merge.
