### ISSUE TITLE
input fields crop text

### ISSUE THREAD

**Issue by pciavald** [particl/partgui#548]
![screenshot_20171223_002015](https://user-images.githubusercontent.com/3384097/34314729-272f54d0-e777-11e7-8691-2927b5c245e3.png)

**Comment by allienworks** [comment]
_note to self:_

`theme.scss:223` add this to `.mat-form-field`:
```
line-height: normal;
```
This should fix it. I've encountered this before, seems like Material is specifically built for Roboto font and other different fonts break it up.
