### ISSUE TITLE
Remove unused components. 

### ISSUE THREAD

**Issue by anandsinghparihar** [particl/partgui#556]
Righ now we have lots of unusable components which are no more used correctly, and if that component is no more used so we should remove it. 
following component: **`grid.component, TableComponent, accordion`** all component etc..

-  Remove unused component (which also not use in feature. )
-  Set return types of all function
-  if no return type then set void 
-  Remove unused includes file
-  Remove unused injected service

**Comment by kewde** [comment]
#558
