### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by vikas-cis** [particl/partgui#557]
![screen shot 2017-12-28 at 3 12 22 pm](https://user-images.githubusercontent.com/20254889/34407059-69a2a0dc-ebe2-11e7-9be0-1b8b2ee99c75.png)

**Comment by anandsinghparihar** [comment]
@vikas-cis I can see button icon is not correct. (New public address, + icon)

**Comment by anandsinghparihar** [comment]
PR: https://github.com/particl/partgui/issues/557
