### ISSUE TITLE
Pagination per page not update while we search (All pages search option Receive/Addressbook)

### ISSUE THREAD

**Issue by vikas-cis** [particl/partgui#560]
How to Reproduce:
1)When you are on address book page, Initially you are on first page and you do the search and get the results correctly.
2)But when you move to second page and try to search result for the same page or previous page result it will not give you any result.

![screen shot 2017-12-29 at 4 03 18 pm](https://user-images.githubusercontent.com/20254889/34435226-f65ec06c-ecb1-11e7-81d9-2e3994e57826.png)
![screen shot 2017-12-29 at 4 03 29 pm](https://user-images.githubusercontent.com/20254889/34435227-f691b684-ecb1-11e7-828e-3ad904a7d7da.png)

**Comment by anandsinghparihar** [comment]
PR: https://github.com/particl/partgui/pull/561
