### ISSUE TITLE
Unlock modal auto close

### ISSUE THREAD

**Issue by HenkSwardt** [particl/partgui#567]
When trying to unlock my wallet the modal close automatically before I can enter my password, on average it takes about 3 seconds to close. 

This can be replicated by launching the unlock modal and waiting a few seconds.

Operating System: Windows 10 64-bit Dev GUI on Testnet. 
Client: 1.1.0
Daemon: 0.15.1.1

**Comment by HenkSwardt** [comment]
Additional note, after restarting the GUI, the password modal now stays open, Will have to see if I can replicate the issue again.

**Comment by pciavald** [comment]
#563 fixes it
