### ISSUE TITLE
Wallet shows created but its not

### ISSUE THREAD

**Issue by anandsinghparihar** [particl/partgui#569]
Initially, when I don't have any new wallet I just creating it in middle of step I just a closed demon and restarted it again, I didn't complete all steps but now I can see wallet has already created so my question is that is that inflow (I guess no).

this is something which is managed by API or let me know how can I restrict front end. because if some user closes demon while creating it they can not even recover it etc..

**Comment by anandsinghparihar** [comment]
as per discussion with @rynomster he said: 
 `if the wallet has been encrypted already.. there is no way to tell if a wallet exists if it is already encrypted`

**Comment by pciavald** [comment]
yeah that's beyond what we can do, just hope the user has saved his key or will recreate the wallet.
