### ISSUE TITLE
Manual wallet update to latest version

### ISSUE THREAD

**Issue by HenkSwardt** [particl/partgui#586]
We have #488 logged to allow for automatically updating wallet to the latest version.  We aim to add this feature in our 1.2 version.

For now can we please add a link at the bottom where we show the wallet version to indicate when a new version is available. This link should then take you to the download page allowing you to manually update the GUI.

**Comment by pciavald** [comment]
![screenshot_20180104_152058](https://user-images.githubusercontent.com/3384097/34567517-e5008eee-f162-11e7-94d6-e69502304228.png)

**Comment by allienworks** [comment]
Why don't we use https://github.com/particl/partgui/pull/493 when the graphics/code is ready? All we need is implement the functionality there..

**Comment by anandsinghparihar** [comment]
I got a Github API for getting latest release I'll add it

`curl -i https://api.github.com/repos/particl/partgui/releases/latest`

**Comment by pciavald** [comment]
moved to #493
