### ISSUE TITLE
Wallet auto-lock delay increased to 5 mins

### ISSUE THREAD

**Issue by HenkSwardt** [particl/partgui#587]
When the wallet is unlocked we automatically lock it after 30 seconds. This is a security feature to ensure your wallet is not left unlocked and unattended. Please change this delay time to 5 mins (300 sec).

**Comment by dasource** [comment]
Please also add a notification on auto lock so the user knows. (bottom left)

**Comment by HenkSwardt** [comment]
Sorry, forgot to add the above, thanks @dasource 

Please include a message as follow after the wallet has locked:
"Wallet auto locked"

**Comment by vikas-cis** [comment]
@HenkSwardt do we need timer to show like "Wallet auto locked 4:59 so on" ?

Thanks

**Comment by anandsinghparihar** [comment]
PR: https://github.com/particl/partgui/pull/589
