### ISSUE TITLE
address book cursor not changing on button

### ISSUE THREAD

**Issue by pciavald** [particl/partgui#591]
in address book : 

![peek 2018-01-04 19-29](https://user-images.githubusercontent.com/3384097/34578545-af5e0578-f185-11e7-91af-e62e2ae021b1.gif)

**Comment by EagleEye25** [comment]
fixed in: https://github.com/particl/partgui/pull/597

**Comment by HenkSwardt** [comment]
@EagleEye25 resolved this for us is #597
