### ISSUE TITLE
creating a wallet : left "wallet" menu appears twice

### ISSUE THREAD

**Issue by pciavald** [particl/partgui#594]
Opening the wallet with no wallet.dat results in poping the create wallet modal. In the sidebar behind, the "Wallet" entry appears twice.

![screenshot_20180104_205741](https://user-images.githubusercontent.com/3384097/34581809-10d06a06-f192-11e7-9477-0cfde9c01031.png)

**Comment by HenkSwardt** [comment]
@EagleEye25 will have a look at this for us.

**Comment by EagleEye25** [comment]
wallet.dat is created as soon as daemon starts up. This modal shows even when there is a wallet.dat, unless it has been encrypted or a private key exists in the wallet.

**Comment by HenkSwardt** [comment]
Issue resolved in #596
