### ISSUE TITLE
lost animation on transaction arrow

### ISSUE THREAD

**Issue by pciavald** [particl/partgui#614]
![peek 2018-01-08 15-09](https://user-images.githubusercontent.com/3384097/34674385-fd3433fa-f485-11e7-943a-23bbcffb9237.gif)

**Comment by allienworks** [comment]
I'm afraid this is not our bug, but rather another quirk of Material's update.
See https://material.angular.io/components/expansion/overview

I vote _not_ to overwrite the default Material stuff in case it would get updated again; we might do way more evil than good. IMO better to use those as they come shipped and build with and around it.
