### ISSUE TITLE
cold staking widget state

### ISSUE THREAD

**Issue by pciavald** [particl/partgui#620]
# unlock cold staking widget

### case

- start wallet
- unlock **cold staking widget**
- wallet is **fully unlocked**
- widget shows **paused**

![peek 2018-01-08 22-08](https://user-images.githubusercontent.com/3384097/34692526-ca5f6df6-f4c0-11e7-9bfa-01cf4d79b44b.gif)

### expected behaviour

- start wallet
- unlock **cold staking widget**
- wallet is **unlocked for staking**
- widget shows **Activation in progress** or **Activated** if at 100%

# full unlock

### case

- start wallet
- **fully unlock** wallet
- widget shows **paused**

![peek 2018-01-08 22-09](https://user-images.githubusercontent.com/3384097/34692538-d390a0a2-f4c0-11e7-97ee-b14cd4981c40.gif)

### expected behaviour

- start wallet
- **fully unlock** wallet
- widget shows **Activation in progress** or **Activated** if at 100%

# staking only

### case

- start wallet
- unlock wallet **for staking only**
- widget is still locked

![peek 2018-01-08 22-10](https://user-images.githubusercontent.com/3384097/34692554-dbb35504-f4c0-11e7-8778-6d4df7281329.gif)

### expected behaviour 

- start wallet
- unlock wallet **for staking only**
- widget shows **Activation in progress** or **Activated** if at 100%

# 100%

### case

- start wallet
- unlock **cold staking widget**
- zap
- balance is at 100% 
- lock wallet
- widget shows **Paused**

![screenshot_20180108_221241](https://user-images.githubusercontent.com/3384097/34692727-61f01d0a-f4c1-11e7-899c-268181bf05f7.png)

### expected behaviour

- start wallet
- unlock **cold staking widget**
- zap
- balance is at 100% 
- widget shows **Activated**

### case

- start wallet
- unlock **cold staking widget**
- zap
- balance is at 100% 
- widget shows **Activation in progress**

![screenshot_20180108_221302](https://user-images.githubusercontent.com/3384097/34692733-68b8fa1c-f4c1-11e7-861d-e5ff54fcf484.png)

### expected behaviour

- start wallet
- unlock **cold staking widget**
- zap
- balance is at 100% 
- widget shows **Activated**

**Comment by pciavald** [comment]
@HenkSwardt

**Comment by anandsinghparihar** [comment]
After entering the cold staking public Key  empty modal is open, So I guess that modal should be close 
![cold staking issue](https://user-images.githubusercontent.com/17725557/34777741-4b99ce12-f641-11e7-9393-5ed986ed0a89.png)

**Comment by pciavald** [comment]
@anandsinghparihar you're right. Please continue discussion in dedicated PR.
