### ISSUE TITLE
1 Sat balance in Blind to display 0 Balance

### ISSUE THREAD

**Issue by HenkSwardt** [particl/partgui#627]
When you select to transfer all from blind to public, the transaction needs to leave 1 sat behind. This now case the blinded balance on SEND page to display as below:

![image](https://user-images.githubusercontent.com/28799964/34736615-406d6e38-f57c-11e7-8555-4fc69ff01fe5.png)

Please display "0" balance in the case of the above scenario.

**Comment by HenkSwardt** [comment]
Based on group discussion we had a look at the following:

Because of the way the blinded txns work you can't transfer all to normal part, it needs to leave a change output of at least 1 sat behind. So for now if balance < 0.000001 then we will display "0" balance

**Comment by kewde** [comment]
Please note that it accumulates, so 2 seperate txns that transfer all coins will leave 2 sats behind (total, because they are 1 sat each).

**Comment by HenkSwardt** [comment]
Following further discussion we have decided to implement the following for this scenario:

If the blind_balance < 1000 sats display a "?" next to blind balance which on hover says the following as a tooltip:

"It is normal to have a very small balance in Blind even after transferring out everything. This is due to the way CT works and part of the privacy feature."
