### ISSUE TITLE
transactions in overview update too slow

### ISSUE THREAD

**Issue by pciavald** [particl/partgui#663]
transaction confirmations in overview update at a too slow rate, i had 4 confirmations in block explorer before seeing them in overview

**Comment by pciavald** [comment]
then we have a bug

**Comment by pciavald** [comment]
![screenshot_20180112_191507](https://user-images.githubusercontent.com/3384097/34889140-3edd5260-f7cd-11e7-8bf8-d3f0b806a440.png)

**Comment by vikas-cis** [comment]
![screen shot 2018-01-15 at 8 18 03 pm](https://user-images.githubusercontent.com/20254889/34948285-b606b504-fa32-11e7-9f2d-f2beb733b4ba.png)
![screen shot 2018-01-15 at 8 18 11 pm](https://user-images.githubusercontent.com/20254889/34948286-b63a4f22-fa32-11e7-8a52-d2adbab96470.png)
![screen shot 2018-01-15 at 8 18 22 pm](https://user-images.githubusercontent.com/20254889/34948287-b6670602-fa32-11e7-9036-42f202873959.png)
![screen shot 2018-01-15 at 8 26 58 pm](https://user-images.githubusercontent.com/20254889/34948288-b6b79ba8-fa32-11e7-8faf-ee8e4bab9826.png)
![screen shot 2018-01-15 at 8 27 17 pm](https://user-images.githubusercontent.com/20254889/34948289-b6e67194-fa32-11e7-9eb7-39ea3eb2c5b4.png)

I was testing on dev branch and its seems updating correctly 👍

**Comment by anandsinghparihar** [comment]
@vikas-cis first check overview page and then check in history then you can see the updates !! new confirmation is not updated!!

**Comment by vikas-cis** [comment]
@anandsinghparihar yeah it seems sometimes it doesn't work properly. I am still doing some testing and trying to debug it 

Thanks
