### ISSUE TITLE
icons not retina friendly

### ISSUE THREAD

**Issue by pciavald** [particl/partgui#680]
seen on a retina macbookpro :

<img width="127" alt="capture d ecran 2018-01-16 a 19 50 14" src="https://user-images.githubusercontent.com/3384097/35006536-2203c61a-faf7-11e7-990b-14370efd370e.png">

**Comment by allienworks** [comment]
Yes, the first two are bitmaps. We should definitely change that, thanks for pointing it out :)

**Comment by allienworks** [comment]
PR open and ready for review/merge ^
